theme: current
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  sendgrid_integration:
    none:
      formatter: sendgrid_integration
      sender: sendgrid_integration
  smtp:
    none:
      formatter: SMTPMailSystem
      sender: SMTPMailSystem
