_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
theme: current
defaults:
  sender: phpmailer_smtp
  formatter: phpmailer_smtp
modules:
  sendgrid_integration:
    none:
      sender: sendgrid_integration
      formatter: sendgrid_integration
  smtp: {  }
