_core:
  default_config_hash: iIf5HmjnxW8tLdod1EQ19q4RQ5mkg-r5wBn2QFmitr8
access_token_expiration: 1800
authorization_code_expiration: 300
refresh_token_expiration: 1209600
token_cron_batch_size: 0
public_key: /home/u359-cpnfwwix7w8a/www/macaws-api.corporaproject.org/public.key
private_key: /home/u359-cpnfwwix7w8a/www/macaws-api.corporaproject.org/private.key
remember_clients: true
use_implicit: true
disable_openid_connect: false
