<?php

/**
 * @file
 * Contains corpus_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function corpus_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the corpus_search module.
    case 'help.page.corpus_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Search API for a Corpus Dataset') . '</p>';
      return $output;

    default:
  }
}
