<?php

/**
 * @file
 * Contains corpus_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function corpus_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the corpus_core module.
    case 'help.page.corpus_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Core functionality for the Corpus distribution') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function corpus_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (in_array($form_id, array('node_text_edit_form', 'node_text_form'))) {
    $fields = array(
      'field_gender',
      'field_semester_in_school',
      'field_college',
      'field_term_writing',
      'field_program',
      'field_assignment',
      'field_draft',
      'field_country',
      'field_filename',
      'field_toefl_listening',
      'field_toefl_reading',
      'field_toefl_speaking',
      'field_toefl_writing',
      'field_toefl_total',
    );
    foreach ($fields as $machine_name) {
      $form[$machine_name]['#weight'] = -1000;
      $form[$machine_name]['#group'] = 'advanced';
      $form[$machine_name]['#open'] = TRUE;
    }
  }
}
