name: 'Corpus Search Configuration'
type: module
core: 8.x
dependencies:
  - block
  - corpus_content_texts
  - facets
  - node
  - rest
  - rest_facets
  - search_api
  - search_api_db
  - search_api_lemma
  - serialization
  - system
  - taxonomy
  - text
  - user
  - views
version: 8.x-1.0
